<?php

return [
    'male' => [
        [
            'age' => 0,
            'severely_underweight' => [0, 2.1],
            'underweight' => [2.2, 2.4],
            'normal' => [2.5, 4.4],
            'overweight' => [4.5, PHP_INT_MAX],
        ],
        [
            'age' => 1,
            'severely_underweight' => [0, 2.9],
            'underweight' => [3.0, 3.3],
            'normal' => [3.4, 5.8],
            'overweight' => [5.9, PHP_INT_MAX],
        ],
        [
            'age' => 2,
            'severely_underweight' => [0, 3.8],
            'underweight' => [3.9, 4.2],
            'normal' => [4.3, 7.1],
            'overweight' => [7.2, PHP_INT_MAX],
        ],
        [
            'age' => 3,
            'severely_underweight' => [0, 4.4],
            'underweight' => [4.5, 4.9],
            'normal' => [5.0, 8.0],
            'overweight' => [8.1, PHP_INT_MAX],
        ],
        [
            'age' => 4,
            'severely_underweight' => [0, 4.9],
            'underweight' => [5.0, 5.5],
            'normal' => [5.6, 8.7],
            'overweight' => [8.8, PHP_INT_MAX],
        ],
        [
            'age' => 5,
            'severely_underweight' => [0, 5.3],
            'underweight' => [5.4, 5.9],
            'normal' => [6.0, 9.3],
            'overweight' => [9.4, PHP_INT_MAX],
        ],
        [
            'age' => 6,
            'severely_underweight' => [0, 5.7],
            'underweight' => [5.8, 6.3],
            'normal' => [6.4, 9.8],
            'overweight' => [9.9, PHP_INT_MAX],
        ],
        [
            'age' => 7,
            'severely_underweight' => [0, 5.9],
            'underweight' => [6.0, 6.6],
            'normal' => [6.7, 10.3],
            'overweight' => [10.4, PHP_INT_MAX],
        ],
        [
            'age' => 8,
            'severely_underweight' => [0, 6.2],
            'underweight' => [6.3, 6.8],
            'normal' => [6.9, 10.7],
            'overweight' => [10.8, PHP_INT_MAX],
        ],
        [
            'age' => 9,
            'severely_underweight' => [0, 6.4],
            'underweight' => [6.5, 7.0],
            'normal' => [7.1, 11.0],
            'overweight' => [11.1, PHP_INT_MAX],
        ],
        [
            'age' => 10,
            'severely_underweight' => [0, 6.6],
            'underweight' => [6.7, 7.3],
            'normal' => [7.4, 11.4],
            'overweight' => [11.5, PHP_INT_MAX],
        ],
        [
            'age' => 11,
            'severely_underweight' => [0, 6.8],
            'underweight' => [6.9, 7.5],
            'normal' => [7.6, 11.7],
            'overweight' => [11.8, PHP_INT_MAX],
        ],
        [
            'age' => 12,
            'severely_underweight' => [0, 6.9],
            'underweight' => [7.0, 7.6],
            'normal' => [7.7, 12.0],
            'overweight' => [12.1, PHP_INT_MAX],
        ],
        [
            'age' => 13,
            'severely_underweight' => [0, 7.1],
            'underweight' => [7.2, 7.8],
            'normal' => [7.9, 12.3],
            'overweight' => [12.4, PHP_INT_MAX],
        ],
        [
            'age' => 14,
            'severely_underweight' => [0, 7.2],
            'underweight' => [7.3, 8.0],
            'normal' => [8.1, 12.6],
            'overweight' => [12.7, PHP_INT_MAX],
        ],
        [
            'age' => 15,
            'severely_underweight' => [0, 7.4],
            'underweight' => [7.4, 8.2],
            'normal' => [8.3, 12.8],
            'overweight' => [12.9, PHP_INT_MAX],
        ],
        [
            'age' => 16,
            'severely_underweight' => [0, 7.5],
            'underweight' => [7.6, 8.3],
            'normal' => [8.4, 13.1],
            'overweight' => [13.2, PHP_INT_MAX],
        ],
        [
            'age' => 17,
            'severely_underweight' => [0, 7.7],
            'underweight' => [7.8, 8.5],
            'normal' => [8.6, 13.4],
            'overweight' => [13.5, PHP_INT_MAX],
        ],
        [
            'age' => 18,
            'severely_underweight' => [0, 7.8],
            'underweight' => [7.9, 8.7],
            'normal' => [8.8, 13.7],
            'overweight' => [13.8, PHP_INT_MAX],
        ],
        [
            'age' => 19,
            'severely_underweight' => [0, 8.0],
            'underweight' => [8.1, 8.8],
            'normal' => [8.9, 13.9],
            'overweight' => [14.0, PHP_INT_MAX],
        ],
        [
            'age' => 20,
            'severely_underweight' => [0, 8.1],
            'underweight' => [8.2, 9.0],
            'normal' => [9.1, 14.2],
            'overweight' => [14.3, PHP_INT_MAX],
        ],
        [
            'age' => 21,
            'severely_underweight' => [0, 8.2],
            'underweight' => [8.3, 9.1],
            'normal' => [9.2, 14.5],
            'overweight' => [14.6, PHP_INT_MAX],
        ],
        [
            'age' => 22,
            'severely_underweight' => [0, 8.4],
            'underweight' => [8.5, 9.3],
            'normal' => [9.4, 14.7],
            'overweight' => [14.8, PHP_INT_MAX],
        ],
        [
            'age' => 23,
            'severely_underweight' => [0, 8.5],
            'underweight' => [8.6, 9.4],
            'normal' => [9.5, 15.0],
            'overweight' => [15.1, PHP_INT_MAX],
        ],
        [
            'age' => 24,
            'severely_underweight' => [0, 8.6],
            'underweight' => [8.7, 9.6],
            'normal' => [9.7, 15.3],
            'overweight' => [15.4, PHP_INT_MAX],
        ],
        [
            'age' => 25,
            'severely_underweight' => [0, 8.8],
            'underweight' => [8.9, 9.7],
            'normal' => [9.8, 15.5],
            'overweight' => [15.6, PHP_INT_MAX],
        ],
        [
            'age' => 26,
            'severely_underweight' => [0, 8.9],
            'underweight' => [9.0, 9.9],
            'normal' => [10.0, 15.8],
            'overweight' => [15.9, PHP_INT_MAX],
        ],
        [
            'age' => 27,
            'severely_underweight' => [0, 9.0],
            'underweight' => [9.1, 10.0],
            'normal' => [10.1, 16.1],
            'overweight' => [16.2, PHP_INT_MAX],
        ],
        [
            'age' => 28,
            'severely_underweight' => [0, 9.1],
            'underweight' => [9.2, 10.1],
            'normal' => [10.2, 16.3],
            'overweight' => [16.4, PHP_INT_MAX],
        ],
        [
            'age' => 29,
            'severely_underweight' => [0, 9.2],
            'underweight' => [9.3, 10.3],
            'normal' => [10.4, 16.6],
            'overweight' => [16.7, PHP_INT_MAX],
        ],
        [
            'age' => 30,
            'severely_underweight' => [0, 9.4],
            'underweight' => [9.5, 10.4],
            'normal' => [10.5, 16.9],
            'overweight' => [17.0, PHP_INT_MAX],
        ],
        [
            'age' => 31,
            'severely_underweight' => [0, 9.5],
            'underweight' => [9.6, 10.6],
            'normal' => [10.7, 17.1],
            'overweight' => [17.2, PHP_INT_MAX],
        ],
        [
            'age' => 32,
            'severely_underweight' => [0, 9.6],
            'underweight' => [9.7, 10.7],
            'normal' => [10.8, 17.4],
            'overweight' => [17.5, PHP_INT_MAX],
        ],
        [
            'age' => 33,
            'severely_underweight' => [0, 9.7],
            'underweight' => [9.8, 10.8],
            'normal' => [10.9, 17.6],
            'overweight' => [17.7, PHP_INT_MAX],
        ],
        [
            'age' => 34,
            'severely_underweight' => [0, 9.8],
            'underweight' => [9.9, 10.9],
            'normal' => [11.0, 17.8],
            'overweight' => [17.9, PHP_INT_MAX],
        ],
        [
            'age' => 35,
            'severely_underweight' => [0, 9.9],
            'underweight' => [10.0, 11.1],
            'normal' => [11.2, 18.1],
            'overweight' => [18.2, PHP_INT_MAX],
        ],
        [
            'age' => 36,
            'severely_underweight' => [0, 10.0],
            'underweight' => [10.1, 11.2],
            'normal' => [11.3, 18.3],
            'overweight' => [18.4, PHP_INT_MAX],
        ],
        [
            'age' => 37,
            'severely_underweight' => [0, 10.1],
            'underweight' => [10.2, 11.3],
            'normal' => [11.4, 18.6],
            'overweight' => [18.7, PHP_INT_MAX],
        ],
        [
            'age' => 38,
            'severely_underweight' => [0, 10.2],
            'underweight' => [10.3, 11.4],
            'normal' => [11.5, 18.8],
            'overweight' => [18.9, PHP_INT_MAX],
        ],
        [
            'age' => 39,
            'severely_underweight' => [0, 10.3],
            'underweight' => [10.4, 11.5],
            'normal' => [11.6, 19.0],
            'overweight' => [19.1, PHP_INT_MAX],
        ],
        [
            'age' => 40 ,
            'severely_underweight' => [0, 10.4],
            'underweight' => [10.5, 11.7],
            'normal' => [11.8, 19.3],
            'overweight' => [19.4, PHP_INT_MAX],
        ],
        [
            'age' => 41 ,
            'severely_underweight' => [0, 10.5],
            'underweight' => [10.6, 11.8],
            'normal' => [11.9, 19.5],
            'overweight' => [19.6, PHP_INT_MAX],
        ],
        [
            'age' => 42 ,
            'severely_underweight' => [0, 10.6],
            'underweight' => [10.7, 11.9],
            'normal' => [12.0, 19.7],
            'overweight' => [19.8, PHP_INT_MAX],
        ],
        [
            'age' => 43 ,
            'severely_underweight' => [0, 10.7],
            'underweight' => [10.8, 12.0],
            'normal' => [12.1, 20.0],
            'overweight' => [20.1, PHP_INT_MAX],
        ],
        [
            'age' => 44 ,
            'severely_underweight' => [0, 10.8],
            'underweight' => [10.9, 12.1],
            'normal' => [12.2, 20.2],
            'overweight' => [20.3, PHP_INT_MAX],
        ],
        [
            'age' => 45 ,
            'severely_underweight' => [0, 10.9],
            'underweight' => [11.0, 12.3],
            'normal' => [12.4, 20.5],
            'overweight' => [20.6, PHP_INT_MAX],
        ],
        [
            'age' => 46 ,
            'severely_underweight' => [0, 11.0],
            'underweight' => [11.1, 12.4],
            'normal' => [12.5, 20.7],
            'overweight' => [20.8, PHP_INT_MAX],
        ],
        [
            'age' => 47 ,
            'severely_underweight' => [0, 11.1],
            'underweight' => [11.2, 12.5],
            'normal' => [12.6, 20.9],
            'overweight' => [21.0, PHP_INT_MAX],
        ],
        [
            'age' => 48 ,
            'severely_underweight' => [0, 11.2],
            'underweight' => [11.3, 12.6],
            'normal' => [12.7, 21.2],
            'overweight' => [21.3, PHP_INT_MAX],
        ],
        [
            'age' => 49 ,
            'severely_underweight' => [0, 11.3],
            'underweight' => [11.4, 12.7],
            'normal' => [12.8, 21.4],
            'overweight' => [21.5, PHP_INT_MAX],
        ],
        [
            'age' => 50 ,
            'severely_underweight' => [0, 11.4],
            'underweight' => [11.5, 12.8],
            'normal' => [12.9, 21.7],
            'overweight' => [21.8, PHP_INT_MAX],
        ],
        [
            'age' => 51 ,
            'severely_underweight' => [0, 11.5],
            'underweight' => [11.6, 13.0],
            'normal' => [13.1, 21.9],
            'overweight' => [22.0, PHP_INT_MAX],
        ],
        [
            'age' => 52 ,
            'severely_underweight' => [0, 11.6],
            'underweight' => [11.7, 13.1],
            'normal' => [13.2, 22.2],
            'overweight' => [22.3, PHP_INT_MAX],
        ],
        [
            'age' => 53 ,
            'severely_underweight' => [0, 11.7],
            'underweight' => [11.8, 13.2],
            'normal' => [13.3, 22.4],
            'overweight' => [22.5, PHP_INT_MAX],
        ],
        [
            'age' => 54 ,
            'severely_underweight' => [0, 11.8],
            'underweight' => [11.9, 13.3],
            'normal' => [13.4, 22.7],
            'overweight' => [22.8, PHP_INT_MAX],
        ],
        [
            'age' => 55 ,
            'severely_underweight' => [0, 11.9],
            'underweight' => [12.0, 13.4],
            'normal' => [13.5, 22.9],
            'overweight' => [23.0, PHP_INT_MAX],
        ],
        [
            'age' => 56 ,
            'severely_underweight' => [0, 12.0],
            'underweight' => [12.1, 13.5],
            'normal' => [13.6, 23.2],
            'overweight' => [23.3, PHP_INT_MAX],
        ],
        [
            'age' => 57 ,
            'severely_underweight' => [0, 12.1],
            'underweight' => [12.2, 13.6],
            'normal' => [13.7, 23.4],
            'overweight' => [23.5, PHP_INT_MAX],
        ],
        [
            'age' => 58 ,
            'severely_underweight' => [0, 12.2],
            'underweight' => [12.3, 13.7],
            'normal' => [13.8, 23.7],
            'overweight' => [23.8, PHP_INT_MAX],
        ],
        [
            'age' => 59 ,
            'severely_underweight' => [0, 12.3],
            'underweight' => [12.4, 13.9],
            'normal' => [14.0, 23.9],
            'overweight' => [24.0, PHP_INT_MAX],
        ],
        [
            'age' => 60 ,
            'severely_underweight' => [0, 12.4],
            'underweight' => [12.5, 14.0],
            'normal' => [14.1, 24.2],
            'overweight' => [24.3, PHP_INT_MAX],
        ],
        [
            'age' => 61 ,
            'severely_underweight' => [0, 12.7],
            'underweight' => [12.8, 14.3],
            'normal' => [14.4, 24.3],
            'overweight' => [24.4, PHP_INT_MAX],
        ],
        [
            'age' => 62 ,
            'severely_underweight' => [0, 12.8],
            'underweight' => [12.9, 14.4],
            'normal' => [14.5, 24.4],
            'overweight' => [24.5, PHP_INT_MAX],
        ],
        [
            'age' => 63 ,
            'severely_underweight' => [0, 13.0],
            'underweight' => [13.1, 14.5],
            'normal' => [14.6, 24.7],
            'overweight' => [24.8, PHP_INT_MAX],
        ],
        [
            'age' => 63 ,
            'severely_underweight' => [0, 13.1],
            'underweight' => [13.2, 14.7],
            'normal' => [14.8, 24.9],
            'overweight' => [25.0, PHP_INT_MAX],
        ],
        [
            'age' => 64 ,
            'severely_underweight' => [0, 13.2],
            'underweight' => [13.3, 14.7],
            'normal' => [14.8, 24.9],
            'overweight' => [25.0, PHP_INT_MAX],
        ],
        [
            'age' => 65 ,
            'severely_underweight' => [0, 13.2],
            'underweight' => [13.3, 14.8],
            'normal' => [14.9, 25.2],
            'overweight' => [25.3, PHP_INT_MAX],
        ],
        [
            'age' => 66 ,
            'severely_underweight' => [0, 13.3],
            'underweight' => [13.4, 14.9],
            'normal' => [15.0, 25.5],
            'overweight' => [25.6, PHP_INT_MAX],
        ],
        [
            'age' => 67 ,
            'severely_underweight' => [0, 13.4],
            'underweight' => [13.5, 15.1],
            'normal' => [15.2, 25.7],
            'overweight' => [25.8, PHP_INT_MAX],
        ],
        [
            'age' => 68 ,
            'severely_underweight' => [0, 13.6],
            'underweight' => [13.7, 15.2],
            'normal' => [15.3, 26.0],
            'overweight' => [26.1, PHP_INT_MAX],
        ],
        [
            'age' => 69 ,
            'severely_underweight' => [0, 13.7],
            'underweight' => [13.8, 15.3],
            'normal' => [15.4, 26.3],
            'overweight' => [26.4, PHP_INT_MAX],
        ],
        [
            'age' => 70 ,
            'severely_underweight' => [0, 13.8],
            'underweight' => [13.9, 15.5],
            'normal' => [15.6, 26.6],
            'overweight' => [26.7, PHP_INT_MAX],
        ],
        [
            'age' => 71,
            'severely_underweight' => [0, 13.9],
            'underweight' => [14.0, 15.6],
            'normal' => [15.7, 26.8],
            'overweight' => [26.9, PHP_INT_MAX],
        ],
            

    ], 

    
    'female' => [
        [
            'age' => 0,
            'severely_underweight' => [0, 2.0],
            'underweight' => [2.1, 2.3],
            'normal' => [2.4, 4.2],
            'overweight' => [4.3, PHP_INT_MAX],
        ],
        [
            'age' => 1,
            'severely_underweight' => [0, 2.7],
            'underweight' => [2.8, 3.1],
            'normal' => [3.2, 5.5],
            'overweight' => [5.6, PHP_INT_MAX],
        ],
        [
            'age' => 2,
            'severely_underweight' => [0, 3.4],
            'underweight' => [3.5, 3.8],
            'normal' => [3.9, 6.6],
            'overweight' => [6.7, PHP_INT_MAX],
        ],
        [
            'age' => 3,
            'severely_underweight' => [0, 4.0],
            'underweight' => [4.1, 4.4],
            'normal' => [4.5, 7.5],
            'overweight' => [7.6, PHP_INT_MAX],
        ],
        [
            'age' => 4,
            'severely_underweight' => [0, 4.4],
            'underweight' => [4.5, 4.9],
            'normal' => [5.0, 8.2],
            'overweight' => [8.3, PHP_INT_MAX],
        ],
        [
            'age' => 5,
            'severely_underweight' => [0, 4.8],
            'underweight' => [4.9, 5.3],
            'normal' => [5.4, 8.8],
            'overweight' => [8.9, PHP_INT_MAX],
        ],
        [
            'age' => 6,
            'severely_underweight' => [0, 5.1],
            'underweight' => [5.2, 5.6],
            'normal' => [5.7, 9.3],
            'overweight' => [9.4, PHP_INT_MAX],
        ],
        [
            'age' => 7,
            'severely_underweight' => [0, 5.3],
            'underweight' => [5.4, 5.9],
            'normal' => [6.0, 9.8],
            'overweight' => [9.9, PHP_INT_MAX],
        ],
        [
            'age' => 8,
            'severely_underweight' => [0, 5.6],
            'underweight' => [5.7, 6.2],
            'normal' => [6.3, 10.2],
            'overweight' => [10.3, PHP_INT_MAX],
        ],
        [
            'age' => 9,
            'severely_underweight' => [0, 5.8],
            'underweight' => [5.9, 6.4],
            'normal' => [6.5, 10.5],
            'overweight' => [10.6, PHP_INT_MAX],
        ],
        [
            'age' => 10,
            'severely_underweight' => [0, 5.9],
            'underweight' => [6.0, 6.6],
            'normal' => [6.7, 10.9],
            'overweight' => [11.0, PHP_INT_MAX],
        ],
        [
            'age' => 11,
            'severely_underweight' => [0, 6.1],
            'underweight' => [6.2, 6.8],
            'normal' => [6.9, 11.2],
            'overweight' => [11.3, PHP_INT_MAX],
        ],
        [
            'age' => 12,
            'severely_underweight' => [0, 6.3],
            'underweight' => [6.4, 6.9],
            'normal' => [7.0, 11.5],
            'overweight' => [11.6, PHP_INT_MAX],
        ],
        [
            'age' => 13,
            'severely_underweight' => [0, 6.4],
            'underweight' => [6.5, 7.1],
            'normal' => [7.2, 11.8],
            'overweight' => [11.9, PHP_INT_MAX],
        ],
        [
            'age' => 14,
            'severely_underweight' => [0, 6.6],
            'underweight' => [6.7, 7.3],
            'normal' => [7.4, 12.1],
            'overweight' => [12.2, PHP_INT_MAX],
        ],
        [
            'age' => 15,
            'severely_underweight' => [0, 6.7],
            'underweight' => [6.8, 7.5],
            'normal' => [7.6, 12.4],
            'overweight' => [12.5, PHP_INT_MAX],
        ],
        [
            'age' => 16,
            'severely_underweight' => [0, 6.9],
            'underweight' => [7.0, 7.6],
            'normal' => [7.7, 12.6],
            'overweight' => [12.7, PHP_INT_MAX],
        ],
        [
            'age' => 17,
            'severely_underweight' => [0, 7.0],
            'underweight' => [7.1, 7.8],
            'normal' => [7.9, 12.9],
            'overweight' => [13.0, PHP_INT_MAX],
        ],
        [
            'age' => 18,
            'severely_underweight' => [0, 7.2],
            'underweight' => [7.3, 8.0],
            'normal' => [8.1, 13.2],
            'overweight' => [13.3, PHP_INT_MAX],
        ],
        [
            'age' => 19,
            'severely_underweight' => [0, 7.3],
            'underweight' => [7.4, 8.1],
            'normal' => [8.2, 13.5],
            'overweight' => [13.6, PHP_INT_MAX],
        ],
        [
            'age' => 20,
            'severely_underweight' => [0, 7.5],
            'underweight' => [7.6, 8.3],
            'normal' => [8.4, 13.7],
            'overweight' => [13.8, PHP_INT_MAX],
        ],
        [
            'age' => 21,
            'severely_underweight' => [0, 7.6],
            'underweight' => [7.7, 8.5],
            'normal' => [8.6, 14.0],
            'overweight' => [14.1, PHP_INT_MAX],
        ],
        [
            'age' => 22,
            'severely_underweight' => [0, 7.8],
            'underweight' => [7.9, 8.6],
            'normal' => [8.7, 14.3],
            'overweight' => [14.4, PHP_INT_MAX],
        ],
        [
            'age' => 23,
            'severely_underweight' => [0, 7.9],
            'underweight' => [8.0, 8.8],
            'normal' => [8.9, 14.6],
            'overweight' => [14.7, PHP_INT_MAX],
        ],
        [
            'age' => 24,
            'severely_underweight' => [0, 8.1],
            'underweight' => [8.2, 8.9],
            'normal' => [9.0, 14.8],
            'overweight' => [14.9, PHP_INT_MAX],
        ],
        [
            'age' => 25,
            'severely_underweight' => [0, 8.2],
            'underweight' => [8.3, 9.1],
            'normal' => [9.2, 15.1],
            'overweight' => [15.2, PHP_INT_MAX],
        ],
        [
            'age' => 26,
            'severely_underweight' => [0, 8.4],
            'underweight' => [8.5, 9.3],
            'normal' => [9.4, 15.4],
            'overweight' => [15.5, PHP_INT_MAX],
        ],
        [
            'age' => 27,
            'severely_underweight' => [0, 8.5],
            'underweight' => [8.6, 9.4],
            'normal' => [9.5, 15.4],
            'overweight' => [15.5, PHP_INT_MAX],
        ],
        [
            'age' => 28,
            'severely_underweight' => [0, 8.6],
            'underweight' => [8.7, 9.6],
            'normal' => [9.7, 16.0],
            'overweight' => [16.1, PHP_INT_MAX],
        ],
        [
            'age' => 29,
            'severely_underweight' => [0, 8.8],
            'underweight' => [8.9, 9.7],
            'normal' => [9.8, 16.2],
            'overweight' => [16.3, PHP_INT_MAX],
        ],
        [
            'age' => 30,
            'severely_underweight' => [0, 8.9],
            'underweight' => [9.0, 9.9],
            'normal' => [10.0, 16.5],
            'overweight' => [16.6, PHP_INT_MAX],
        ],
        [
            'age' => 31,
            'severely_underweight' => [0, 9.0],
            'underweight' => [9.1, 10.0],
            'normal' => [10.1, 16.8],
            'overweight' => [16.9, PHP_INT_MAX],
        ],
        [
            'age' => 32,
            'severely_underweight' => [0, 9.1],
            'underweight' => [9.2, 10.2],
            'normal' => [10.3, 17.1],
            'overweight' => [17.2, PHP_INT_MAX],
        ],
        [
            'age' => 33,
            'severely_underweight' => [0, 9.3],
            'underweight' => [9.4, 10.3],
            'normal' => [10.4, 17.3],
            'overweight' => [17.4, PHP_INT_MAX],
        ],
        [
            'age' => 34,
            'severely_underweight' => [0, 9.4],
            'underweight' => [9.5, 10.4],
            'normal' => [10.5, 17.6],
            'overweight' => [17.7, PHP_INT_MAX],
        ],
        [
            'age' => 35,
            'severely_underweight' => [0, 9.5],
            'underweight' => [9.6, 10.6],
            'normal' => [10.7, 17.9],
            'overweight' => [18.0, PHP_INT_MAX],
        ],
        [
            'age' => 36,
            'severely_underweight' => [0, 9.6],
            'underweight' => [9.7, 10.7],
            'normal' => [10.8, 18.1],
            'overweight' => [18.2, PHP_INT_MAX],
        ],
        [
            'age' => 37,
            'severely_underweight' => [0, 9.7],
            'underweight' => [9.8, 10.8],
            'normal' => [10.9, 18.4],
            'overweight' => [18.5, PHP_INT_MAX],
        ],
        [
            'age' => 38,
            'severely_underweight' => [0, 9.8],
            'underweight' => [9.9, 11.0],
            'normal' => [11.1, 18.7],
            'overweight' => [18.8, PHP_INT_MAX],
        ],
        [
            'age' => 39,
            'severely_underweight' => [0, 9.9],
            'underweight' => [10.0, 11.1],
            'normal' => [11.2, 19.0],
            'overweight' => [19.1, PHP_INT_MAX],
        ],
        [
            'age' => 40,
            'severely_underweight' => [0, 10.1],
            'underweight' => [10.2, 11.2],
            'normal' => [11.3, 19.2],
            'overweight' => [19.3, PHP_INT_MAX],
        ],
        [
            'age' => 41,
            'severely_underweight' => [0, 10.2],
            'underweight' => [10.3, 11.4],
            'normal' => [11.5, 19.5],
            'overweight' => [19.6, PHP_INT_MAX],
        ],
        [
            'age' => 42,
            'severely_underweight' => [0, 10.3],
            'underweight' => [10.4, 11.5],
            'normal' => [11.6, 19.8],
            'overweight' => [19.9, PHP_INT_MAX],
        ],
        [
            'age' => 43,
            'severely_underweight' => [0, 10.4],
            'underweight' => [10.5, 11.6],
            'normal' => [11.7, 20.1],
            'overweight' => [20.2, PHP_INT_MAX],
        ],
        [
            'age' => 44,
            'severely_underweight' => [0, 10.5],
            'underweight' => [10.6, 11.7],
            'normal' => [11.8, 20.4],
            'overweight' => [20.5, PHP_INT_MAX],
        ],
        [
            'age' => 45,
            'severely_underweight' => [0, 10.6],
            'underweight' => [10.7, 11.9],
            'normal' => [12.0, 20.7],
            'overweight' => [20.8, PHP_INT_MAX],
        ],
        [
            'age' => 46,
            'severely_underweight' => [0, 10.7],
            'underweight' => [10.8, 12.0],
            'normal' => [12.1, 20.9],
            'overweight' => [21.0, PHP_INT_MAX],
        ],
        [
            'age' => 47,
            'severely_underweight' => [0, 10.8],
            'underweight' => [10.9, 12.1],
            'normal' => [12.2, 21.2],
            'overweight' => [21.3, PHP_INT_MAX],
        ],
        [
            'age' => 48,
            'severely_underweight' => [0, 10.9],
            'underweight' => [11.0, 12.2],
            'normal' => [12.3, 21.5],
            'overweight' => [21.6, PHP_INT_MAX],
        ],
        [
            'age' => 49,
            'severely_underweight' => [0, 11.0],
            'underweight' => [11.1, 12.3],
            'normal' => [12.4, 21.8],
            'overweight' => [21.9, PHP_INT_MAX],
        ],
        [
            'age' => 50,
            'severely_underweight' => [0, 11.1],
            'underweight' => [11.2, 12.4],
            'normal' => [12.5, 22.1],
            'overweight' => [22.3, PHP_INT_MAX],
        ],
        [
            'age' => 51,
            'severely_underweight' => [0, 11.2],
            'underweight' => [11.3, 12.6],
            'normal' => [12.7, 22.4],
            'overweight' => [22.5, PHP_INT_MAX],
        ],
        [
            'age' => 52,
            'severely_underweight' => [0, 11.3],
            'underweight' => [11.4, 12.7],
            'normal' => [12.8, 22.6],
            'overweight' => [22.7, PHP_INT_MAX],
        ],
        [
            'age' => 53,
            'severely_underweight' => [0, 11.4],
            'underweight' => [11.5, 12.8],
            'normal' => [12.9, 22.9],
            'overweight' => [23.0, PHP_INT_MAX],
        ],
        [
            'age' => 54,
            'severely_underweight' => [0, 11.5],
            'underweight' => [11.6, 12.9],
            'normal' => [13.0, 23.2],
            'overweight' => [23.3, PHP_INT_MAX],
        ],
        [
            'age' => 55,
            'severely_underweight' => [0, 11.6],
            'underweight' => [11.7, 13.1],
            'normal' => [13.2, 23.5],
            'overweight' => [23.6, PHP_INT_MAX],
        ],
        [
            'age' => 56,
            'severely_underweight' => [0, 11.7],
            'underweight' => [11.8, 13.2],
            'normal' => [13.3, 23.8],
            'overweight' => [23.9, PHP_INT_MAX],
        ],
        [
            'age' => 57,
            'severely_underweight' => [0, 11.8],
            'underweight' => [11.9, 13.3],
            'normal' => [13.4, 24.1],
            'overweight' => [24.2, PHP_INT_MAX],
        ],
        [
            'age' => 58,
            'severely_underweight' => [0, 11.9],
            'underweight' => [12.0, 13.4],
            'normal' => [13.5, 24.4],
            'overweight' => [24.5, PHP_INT_MAX],
        ],
        [
            'age' => 59,
            'severely_underweight' => [0, 12.0],
            'underweight' => [12.1, 13.5],
            'normal' => [13.6, 24.6],
            'overweight' => [24.7, PHP_INT_MAX],
        ],
        [
            'age' => 60,
            'severely_underweight' => [0, 12.1],
            'underweight' => [12.2, 13.6],
            'normal' => [13.7, 24.7],
            'overweight' => [24.8, PHP_INT_MAX],
        ],
        [
            'age' => 61,
            'severely_underweight' => [0, 12.4],
            'underweight' => [12.5, 13.9],
            'normal' => [14.0, 24.8],
            'overweight' => [24.9, PHP_INT_MAX],
        ],
        [
            'age' => 62,
            'severely_underweight' => [0, 12.5],
            'underweight' => [12.6, 14.0],
            'normal' => [14.1, 25.1],
            'overweight' => [25.2, PHP_INT_MAX],
        ],
        [
            'age' => 63,
            'severely_underweight' => [0, 12.6],
            'underweight' => [12.7, 14.1],
            'normal' => [14.2, 25.4],
            'overweight' => [25.5, PHP_INT_MAX],
        ],
        [
            'age' => 64,
            'severely_underweight' => [0, 12.7],
            'underweight' => [12.8, 14.2],
            'normal' => [14.3, 25.6],
            'overweight' => [25.7, PHP_INT_MAX],
        ],
        [
            'age' => 65,
            'severely_underweight' => [0, 12.8],
            'underweight' => [12.9, 14.3],
            'normal' => [14.4, 25.9],
            'overweight' => [26.0, PHP_INT_MAX],
        ],
        [
            'age' => 66,
            'severely_underweight' => [0, 12.9],
            'underweight' => [13.0, 14.5],
            'normal' => [14.6, 26.2],
            'overweight' => [26.3, PHP_INT_MAX],
        ],
        [
            'age' => 67,
            'severely_underweight' => [0, 13.0],
            'underweight' => [13.1, 14.6],
            'normal' => [14.7, 26.5],
            'overweight' => [26.6, PHP_INT_MAX],
        ],
        [
            'age' => 68,
            'severely_underweight' => [0, 13.1],
            'underweight' => [13.2, 14.7],
            'normal' => [14.8, 26.7],
            'overweight' => [26.8, PHP_INT_MAX],
        ],
        [
            'age' => 69,
            'severely_underweight' => [0, 13.2],
            'underweight' => [13.3, 14.8],
            'normal' => [14.9, 27.0],
            'overweight' => [27.1, PHP_INT_MAX],
        ],
        [
            'age' => 70,
            'severely_underweight' => [0, 13.3],
            'underweight' => [13.4, 14.9],
            'normal' => [15.0, 27.3],
            'overweight' => [27.4, PHP_INT_MAX],
        ],
        [
            'age' => 71,
            'severely_underweight' => [0, 13.4],
            'underweight' => [13.5, 15.1],
            'normal' => [15.2, 27.6],
            'overweight' => [27.7, PHP_INT_MAX],
        ],
    ]
];
        